// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID       int64              `json:"id"`
	Ts       pgtype.Timestamptz `json:"ts"`
	UserID   pgtype.UUID        `json:"user_id"`
	Actor    string             `json:"actor"`
	Action   string             `json:"action"`
	Target   string             `json:"target"`
	Metadata []byte             `json:"metadata"`
}

type Disk struct {
	ID        pgtype.UUID        `json:"id"`
	MachineID pgtype.UUID        `json:"machine_id"`
	SizeMib   int32              `json:"size_mib"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GithubLink struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Metadata  []byte             `json:"metadata"`
	SecretRef string             `json:"secret_ref"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Host struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	AgentUrl  string             `json:"agent_url"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Machine struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	State        string             `json:"state"`
	HostID       pgtype.UUID        `json:"host_id"`
	VmHandle     *string            `json:"vm_handle"`
	GuestIp      *netip.Addr        `json:"guest_ip"`
	KernelRef    string             `json:"kernel_ref"`
	RootfsRef    string             `json:"rootfs_ref"`
	ResourceSpec []byte             `json:"resource_spec"`
	LastError    *string            `json:"last_error"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DiskID       pgtype.UUID        `json:"disk_id"`
	Boot         *string            `json:"boot"`
	Name         string             `json:"name"`
}

type MachineEvent struct {
	ID        int64              `json:"id"`
	MachineID pgtype.UUID        `json:"machine_id"`
	Type      string             `json:"type"`
	FromState *string            `json:"from_state"`
	ToState   *string            `json:"to_state"`
	Actor     string             `json:"actor"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Provider struct {
	Key           string             `json:"key"`
	DisplayName   string             `json:"display_name"`
	LaunchCommand string             `json:"launch_command"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SecretFields  []byte             `json:"secret_fields"`
	SetupCommand  *string            `json:"setup_command"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Snapshot struct {
	MachineID pgtype.UUID        `json:"machine_id"`
	FcVersion string             `json:"fc_version"`
	MemBytes  int64              `json:"mem_bytes"`
	KernelRef string             `json:"kernel_ref"`
	RootfsRef string             `json:"rootfs_ref"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	GithubUserID int64              `json:"github_user_id"`
	Login        string             `json:"login"`
	Email        string             `json:"email"`
	AvatarUrl    string             `json:"avatar_url"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
