// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GithubLink struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Metadata  []byte             `json:"metadata"`
	SecretRef string             `json:"secret_ref"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	GithubUserID int64              `json:"github_user_id"`
	Login        string             `json:"login"`
	Email        string             `json:"email"`
	AvatarUrl    string             `json:"avatar_url"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
