// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, created_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getGitHubLink = `-- name: GetGitHubLink :one
SELECT user_id, metadata, secret_ref, created_at, updated_at FROM github_links WHERE user_id = $1
`

func (q *Queries) GetGitHubLink(ctx context.Context, userID pgtype.UUID) (GithubLink, error) {
	row := q.db.QueryRow(ctx, getGitHubLink, userID)
	var i GithubLink
	err := row.Scan(
		&i.UserID,
		&i.Metadata,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    sessions.id, sessions.user_id, sessions.token_hash, sessions.created_at, sessions.expires_at, sessions.revoked_at,
    users.id, users.github_user_id, users.login, users.email, users.avatar_url, users.status, users.created_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.expires_at > now()
`

type GetSessionByTokenHashRow struct {
	Session Session `json:"session"`
	User    User    `json:"user"`
}

// Look up a live (unexpired, unrevoked) session by its token hash, returning
// the session together with the owning user.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.CreatedAt,
		&i.Session.ExpiresAt,
		&i.Session.RevokedAt,
		&i.User.ID,
		&i.User.GithubUserID,
		&i.User.Login,
		&i.User.Email,
		&i.User.AvatarUrl,
		&i.User.Status,
		&i.User.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_user_id, login, email, avatar_url, status, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.Login,
		&i.Email,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET expires_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Slide the expiry forward on use (sliding-refresh sessions).
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}

const upsertGitHubLink = `-- name: UpsertGitHubLink :one
INSERT INTO github_links (user_id, metadata, secret_ref, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE
    SET metadata = EXCLUDED.metadata,
        secret_ref = EXCLUDED.secret_ref,
        updated_at = now()
RETURNING user_id, metadata, secret_ref, created_at, updated_at
`

type UpsertGitHubLinkParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Metadata  []byte      `json:"metadata"`
	SecretRef string      `json:"secret_ref"`
}

func (q *Queries) UpsertGitHubLink(ctx context.Context, arg UpsertGitHubLinkParams) (GithubLink, error) {
	row := q.db.QueryRow(ctx, upsertGitHubLink, arg.UserID, arg.Metadata, arg.SecretRef)
	var i GithubLink
	err := row.Scan(
		&i.UserID,
		&i.Metadata,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (github_user_id, login, email, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (github_user_id) DO UPDATE
    SET login = EXCLUDED.login,
        email = EXCLUDED.email,
        avatar_url = EXCLUDED.avatar_url
RETURNING id, github_user_id, login, email, avatar_url, status, created_at
`

type UpsertUserParams struct {
	GithubUserID int64  `json:"github_user_id"`
	Login        string `json:"login"`
	Email        string `json:"email"`
	AvatarUrl    string `json:"avatar_url"`
}

// Insert a user keyed by their GitHub user id, updating profile fields on
// repeat logins. Returns the full row (id is stable across logins).
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GithubUserID,
		arg.Login,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.Login,
		&i.Email,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
