// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDisk = `-- name: CreateDisk :one
INSERT INTO disks (machine_id, size_mib)
VALUES ($1, $2)
RETURNING id, machine_id, size_mib, created_at
`

type CreateDiskParams struct {
	MachineID pgtype.UUID `json:"machine_id"`
	SizeMib   int32       `json:"size_mib"`
}

// Provision a machine's persistent disk at create time (1:1 with the machine).
func (q *Queries) CreateDisk(ctx context.Context, arg CreateDiskParams) (Disk, error) {
	row := q.db.QueryRow(ctx, createDisk, arg.MachineID, arg.SizeMib)
	var i Disk
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.SizeMib,
		&i.CreatedAt,
	)
	return i, err
}

const createMachine = `-- name: CreateMachine :one
INSERT INTO machines (user_id, host_id, state, kernel_ref, rootfs_ref, resource_spec)
VALUES ($1, $2, 'requested', $3, $4, $5)
RETURNING id, user_id, state, host_id, vm_handle, guest_ip, kernel_ref, rootfs_ref, resource_spec, last_error, last_active_at, created_at, updated_at, disk_id, boot
`

type CreateMachineParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	HostID       pgtype.UUID `json:"host_id"`
	KernelRef    string      `json:"kernel_ref"`
	RootfsRef    string      `json:"rootfs_ref"`
	ResourceSpec []byte      `json:"resource_spec"`
}

// Create a user's (1:1) machine in the initial 'requested' state, pinning the
// image refs and resource spec for the lifetime of the row.
func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, createMachine,
		arg.UserID,
		arg.HostID,
		arg.KernelRef,
		arg.RootfsRef,
		arg.ResourceSpec,
	)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.State,
		&i.HostID,
		&i.VmHandle,
		&i.GuestIp,
		&i.KernelRef,
		&i.RootfsRef,
		&i.ResourceSpec,
		&i.LastError,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiskID,
		&i.Boot,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, created_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteSnapshot = `-- name: DeleteSnapshot :exec
DELETE FROM snapshots WHERE machine_id = $1
`

func (q *Queries) DeleteSnapshot(ctx context.Context, machineID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSnapshot, machineID)
	return err
}

const getDiskByMachineID = `-- name: GetDiskByMachineID :one
SELECT id, machine_id, size_mib, created_at FROM disks WHERE machine_id = $1
`

func (q *Queries) GetDiskByMachineID(ctx context.Context, machineID pgtype.UUID) (Disk, error) {
	row := q.db.QueryRow(ctx, getDiskByMachineID, machineID)
	var i Disk
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.SizeMib,
		&i.CreatedAt,
	)
	return i, err
}

const getGitHubLink = `-- name: GetGitHubLink :one
SELECT user_id, metadata, secret_ref, created_at, updated_at FROM github_links WHERE user_id = $1
`

func (q *Queries) GetGitHubLink(ctx context.Context, userID pgtype.UUID) (GithubLink, error) {
	row := q.db.QueryRow(ctx, getGitHubLink, userID)
	var i GithubLink
	err := row.Scan(
		&i.UserID,
		&i.Metadata,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMachineByID = `-- name: GetMachineByID :one
SELECT id, user_id, state, host_id, vm_handle, guest_ip, kernel_ref, rootfs_ref, resource_spec, last_error, last_active_at, created_at, updated_at, disk_id, boot FROM machines WHERE id = $1
`

func (q *Queries) GetMachineByID(ctx context.Context, id pgtype.UUID) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachineByID, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.State,
		&i.HostID,
		&i.VmHandle,
		&i.GuestIp,
		&i.KernelRef,
		&i.RootfsRef,
		&i.ResourceSpec,
		&i.LastError,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiskID,
		&i.Boot,
	)
	return i, err
}

const getMachineByUserID = `-- name: GetMachineByUserID :one
SELECT id, user_id, state, host_id, vm_handle, guest_ip, kernel_ref, rootfs_ref, resource_spec, last_error, last_active_at, created_at, updated_at, disk_id, boot FROM machines WHERE user_id = $1
`

func (q *Queries) GetMachineByUserID(ctx context.Context, userID pgtype.UUID) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachineByUserID, userID)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.State,
		&i.HostID,
		&i.VmHandle,
		&i.GuestIp,
		&i.KernelRef,
		&i.RootfsRef,
		&i.ResourceSpec,
		&i.LastError,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiskID,
		&i.Boot,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT key, display_name, launch_command, enabled, created_at, secret_fields, setup_command FROM providers WHERE key = $1
`

func (q *Queries) GetProvider(ctx context.Context, key string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, key)
	var i Provider
	err := row.Scan(
		&i.Key,
		&i.DisplayName,
		&i.LaunchCommand,
		&i.Enabled,
		&i.CreatedAt,
		&i.SecretFields,
		&i.SetupCommand,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    sessions.id, sessions.user_id, sessions.token_hash, sessions.created_at, sessions.expires_at, sessions.revoked_at,
    users.id, users.github_user_id, users.login, users.email, users.avatar_url, users.status, users.created_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.expires_at > now()
`

type GetSessionByTokenHashRow struct {
	Session Session `json:"session"`
	User    User    `json:"user"`
}

// Look up a live (unexpired, unrevoked) session by its token hash, returning
// the session together with the owning user.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.CreatedAt,
		&i.Session.ExpiresAt,
		&i.Session.RevokedAt,
		&i.User.ID,
		&i.User.GithubUserID,
		&i.User.Login,
		&i.User.Email,
		&i.User.AvatarUrl,
		&i.User.Status,
		&i.User.CreatedAt,
	)
	return i, err
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT machine_id, fc_version, mem_bytes, kernel_ref, rootfs_ref, created_at FROM snapshots WHERE machine_id = $1
`

func (q *Queries) GetSnapshot(ctx context.Context, machineID pgtype.UUID) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshot, machineID)
	var i Snapshot
	err := row.Scan(
		&i.MachineID,
		&i.FcVersion,
		&i.MemBytes,
		&i.KernelRef,
		&i.RootfsRef,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_user_id, login, email, avatar_url, status, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.Login,
		&i.Email,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (user_id, actor, action, target, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ts, user_id, actor, action, target, metadata
`

type InsertAuditLogParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Actor    string      `json:"actor"`
	Action   string      `json:"action"`
	Target   string      `json:"target"`
	Metadata []byte      `json:"metadata"`
}

// Append one audit row. user_id may be NULL for system actors (the injector).
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserID,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.UserID,
		&i.Actor,
		&i.Action,
		&i.Target,
		&i.Metadata,
	)
	return i, err
}

const insertMachineEvent = `-- name: InsertMachineEvent :one
INSERT INTO machine_events (machine_id, type, from_state, to_state, actor, payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, machine_id, type, from_state, to_state, actor, payload, created_at
`

type InsertMachineEventParams struct {
	MachineID pgtype.UUID `json:"machine_id"`
	Type      string      `json:"type"`
	FromState *string     `json:"from_state"`
	ToState   *string     `json:"to_state"`
	Actor     string      `json:"actor"`
	Payload   []byte      `json:"payload"`
}

// Append one audit row. Always called in the same tx as the state change it
// records (see internal/machine.Transition).
func (q *Queries) InsertMachineEvent(ctx context.Context, arg InsertMachineEventParams) (MachineEvent, error) {
	row := q.db.QueryRow(ctx, insertMachineEvent,
		arg.MachineID,
		arg.Type,
		arg.FromState,
		arg.ToState,
		arg.Actor,
		arg.Payload,
	)
	var i MachineEvent
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Type,
		&i.FromState,
		&i.ToState,
		&i.Actor,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listMachineEventsAfter = `-- name: ListMachineEventsAfter :many
SELECT id, machine_id, type, from_state, to_state, actor, payload, created_at FROM machine_events
WHERE machine_id = $1 AND id > $2
ORDER BY id ASC
`

type ListMachineEventsAfterParams struct {
	MachineID pgtype.UUID `json:"machine_id"`
	ID        int64       `json:"id"`
}

// Events for a machine after a given event id, for SSE Last-Event-ID replay.
func (q *Queries) ListMachineEventsAfter(ctx context.Context, arg ListMachineEventsAfterParams) ([]MachineEvent, error) {
	rows, err := q.db.Query(ctx, listMachineEventsAfter, arg.MachineID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MachineEvent{}
	for rows.Next() {
		var i MachineEvent
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.Type,
			&i.FromState,
			&i.ToState,
			&i.Actor,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachineEventsRecent = `-- name: ListMachineEventsRecent :many
SELECT id, machine_id, type, from_state, to_state, actor, payload, created_at FROM (
    SELECT id, machine_id, type, from_state, to_state, actor, payload, created_at FROM machine_events
    WHERE machine_id = $1
    ORDER BY id DESC
    LIMIT $2
) sub
ORDER BY id ASC
`

type ListMachineEventsRecentParams struct {
	MachineID pgtype.UUID `json:"machine_id"`
	Limit     int32       `json:"limit"`
}

// Most-recent N events for a machine, returned oldest-first for the SSE
// snapshot.
func (q *Queries) ListMachineEventsRecent(ctx context.Context, arg ListMachineEventsRecentParams) ([]MachineEvent, error) {
	rows, err := q.db.Query(ctx, listMachineEventsRecent, arg.MachineID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MachineEvent{}
	for rows.Next() {
		var i MachineEvent
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.Type,
			&i.FromState,
			&i.ToState,
			&i.Actor,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachinesInStates = `-- name: ListMachinesInStates :many
SELECT id, user_id, state, host_id, vm_handle, guest_ip, kernel_ref, rootfs_ref, resource_spec, last_error, last_active_at, created_at, updated_at, disk_id, boot FROM machines WHERE state = ANY($1::text[]) ORDER BY updated_at ASC
`

// Used by the poller to find transitional machines to advance and running
// machines to sweep.
func (q *Queries) ListMachinesInStates(ctx context.Context, dollar_1 []string) ([]Machine, error) {
	rows, err := q.db.Query(ctx, listMachinesInStates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Machine{}
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.State,
			&i.HostID,
			&i.VmHandle,
			&i.GuestIp,
			&i.KernelRef,
			&i.RootfsRef,
			&i.ResourceSpec,
			&i.LastError,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DiskID,
			&i.Boot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT key, display_name, launch_command, enabled, created_at, secret_fields, setup_command FROM providers ORDER BY key
`

// The provider registry, ordered for stable API output.
func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.Key,
			&i.DisplayName,
			&i.LaunchCommand,
			&i.Enabled,
			&i.CreatedAt,
			&i.SecretFields,
			&i.SetupCommand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
RETURNING id
`

// Revoke a live session by token hash, returning its id so the gateway can
// close any in-process WebSockets bound to it. No row (ErrNoRows) means the
// token was unknown or already revoked — a no-op.
func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, revokeSession, tokenHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const setMachineBoot = `-- name: SetMachineBoot :one
UPDATE machines SET boot = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, state, host_id, vm_handle, guest_ip, kernel_ref, rootfs_ref, resource_spec, last_error, last_active_at, created_at, updated_at, disk_id, boot
`

type SetMachineBootParams struct {
	ID   pgtype.UUID `json:"id"`
	Boot *string     `json:"boot"`
}

// Record how the current run started ('cold' | 'resumed'); pass NULL to clear.
func (q *Queries) SetMachineBoot(ctx context.Context, arg SetMachineBootParams) (Machine, error) {
	row := q.db.QueryRow(ctx, setMachineBoot, arg.ID, arg.Boot)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.State,
		&i.HostID,
		&i.VmHandle,
		&i.GuestIp,
		&i.KernelRef,
		&i.RootfsRef,
		&i.ResourceSpec,
		&i.LastError,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiskID,
		&i.Boot,
	)
	return i, err
}

const setMachineDisk = `-- name: SetMachineDisk :one
UPDATE machines SET disk_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, state, host_id, vm_handle, guest_ip, kernel_ref, rootfs_ref, resource_spec, last_error, last_active_at, created_at, updated_at, disk_id, boot
`

type SetMachineDiskParams struct {
	ID     pgtype.UUID `json:"id"`
	DiskID pgtype.UUID `json:"disk_id"`
}

// Attach the just-created disk to the machine row.
func (q *Queries) SetMachineDisk(ctx context.Context, arg SetMachineDiskParams) (Machine, error) {
	row := q.db.QueryRow(ctx, setMachineDisk, arg.ID, arg.DiskID)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.State,
		&i.HostID,
		&i.VmHandle,
		&i.GuestIp,
		&i.KernelRef,
		&i.RootfsRef,
		&i.ResourceSpec,
		&i.LastError,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiskID,
		&i.Boot,
	)
	return i, err
}

const setMachineRuntime = `-- name: SetMachineRuntime :one
UPDATE machines
SET vm_handle = $2,
    guest_ip = $3,
    last_active_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, state, host_id, vm_handle, guest_ip, kernel_ref, rootfs_ref, resource_spec, last_error, last_active_at, created_at, updated_at, disk_id, boot
`

type SetMachineRuntimeParams struct {
	ID       pgtype.UUID `json:"id"`
	VmHandle *string     `json:"vm_handle"`
	GuestIp  *netip.Addr `json:"guest_ip"`
}

// Record runtime facts reported by the node-agent (handle + allocated guest IP)
// once a machine is provisioned.
func (q *Queries) SetMachineRuntime(ctx context.Context, arg SetMachineRuntimeParams) (Machine, error) {
	row := q.db.QueryRow(ctx, setMachineRuntime, arg.ID, arg.VmHandle, arg.GuestIp)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.State,
		&i.HostID,
		&i.VmHandle,
		&i.GuestIp,
		&i.KernelRef,
		&i.RootfsRef,
		&i.ResourceSpec,
		&i.LastError,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiskID,
		&i.Boot,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET expires_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Slide the expiry forward on use (sliding-refresh sessions).
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}

const updateMachineState = `-- name: UpdateMachineState :one
UPDATE machines
SET state = $1,
    last_error = $2,
    updated_at = now()
WHERE id = $3 AND state = $4
RETURNING id, user_id, state, host_id, vm_handle, guest_ip, kernel_ref, rootfs_ref, resource_spec, last_error, last_active_at, created_at, updated_at, disk_id, boot
`

type UpdateMachineStateParams struct {
	ToState   string      `json:"to_state"`
	LastError *string     `json:"last_error"`
	ID        pgtype.UUID `json:"id"`
	FromState string      `json:"from_state"`
}

// Guarded compare-and-set transition: only updates if the row is still in the
// expected from-state, so illegal/raced transitions affect zero rows (the Go
// layer turns that into ErrInvalidTransition). last_error is set on the same
// write (pass NULL to clear it on a successful forward transition).
func (q *Queries) UpdateMachineState(ctx context.Context, arg UpdateMachineStateParams) (Machine, error) {
	row := q.db.QueryRow(ctx, updateMachineState,
		arg.ToState,
		arg.LastError,
		arg.ID,
		arg.FromState,
	)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.State,
		&i.HostID,
		&i.VmHandle,
		&i.GuestIp,
		&i.KernelRef,
		&i.RootfsRef,
		&i.ResourceSpec,
		&i.LastError,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiskID,
		&i.Boot,
	)
	return i, err
}

const upsertGitHubLink = `-- name: UpsertGitHubLink :one
INSERT INTO github_links (user_id, metadata, secret_ref, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE
    SET metadata = EXCLUDED.metadata,
        secret_ref = EXCLUDED.secret_ref,
        updated_at = now()
RETURNING user_id, metadata, secret_ref, created_at, updated_at
`

type UpsertGitHubLinkParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Metadata  []byte      `json:"metadata"`
	SecretRef string      `json:"secret_ref"`
}

func (q *Queries) UpsertGitHubLink(ctx context.Context, arg UpsertGitHubLinkParams) (GithubLink, error) {
	row := q.db.QueryRow(ctx, upsertGitHubLink, arg.UserID, arg.Metadata, arg.SecretRef)
	var i GithubLink
	err := row.Scan(
		&i.UserID,
		&i.Metadata,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHostByName = `-- name: UpsertHostByName :one
INSERT INTO hosts (name, agent_url)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE
    SET agent_url = EXCLUDED.agent_url
RETURNING id, name, agent_url, status, created_at
`

type UpsertHostByNameParams struct {
	Name     string `json:"name"`
	AgentUrl string `json:"agent_url"`
}

// Seed/refresh a host by its unique name at control-plane startup.
func (q *Queries) UpsertHostByName(ctx context.Context, arg UpsertHostByNameParams) (Host, error) {
	row := q.db.QueryRow(ctx, upsertHostByName, arg.Name, arg.AgentUrl)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AgentUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSnapshot = `-- name: UpsertSnapshot :one
INSERT INTO snapshots (machine_id, fc_version, mem_bytes, kernel_ref, rootfs_ref)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (machine_id) DO UPDATE
    SET fc_version = EXCLUDED.fc_version,
        mem_bytes  = EXCLUDED.mem_bytes,
        kernel_ref = EXCLUDED.kernel_ref,
        rootfs_ref = EXCLUDED.rootfs_ref,
        created_at = now()
RETURNING machine_id, fc_version, mem_bytes, kernel_ref, rootfs_ref, created_at
`

type UpsertSnapshotParams struct {
	MachineID pgtype.UUID `json:"machine_id"`
	FcVersion string      `json:"fc_version"`
	MemBytes  int64       `json:"mem_bytes"`
	KernelRef string      `json:"kernel_ref"`
	RootfsRef string      `json:"rootfs_ref"`
}

// Record (replacing) the machine's current hibernation snapshot metadata. One
// row per machine; consumed on resume / invalidated on cold stop via DeleteSnapshot.
func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, upsertSnapshot,
		arg.MachineID,
		arg.FcVersion,
		arg.MemBytes,
		arg.KernelRef,
		arg.RootfsRef,
	)
	var i Snapshot
	err := row.Scan(
		&i.MachineID,
		&i.FcVersion,
		&i.MemBytes,
		&i.KernelRef,
		&i.RootfsRef,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (github_user_id, login, email, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (github_user_id) DO UPDATE
    SET login = EXCLUDED.login,
        email = EXCLUDED.email,
        avatar_url = EXCLUDED.avatar_url
RETURNING id, github_user_id, login, email, avatar_url, status, created_at
`

type UpsertUserParams struct {
	GithubUserID int64  `json:"github_user_id"`
	Login        string `json:"login"`
	Email        string `json:"email"`
	AvatarUrl    string `json:"avatar_url"`
}

// Insert a user keyed by their GitHub user id, updating profile fields on
// repeat logins. Returns the full row (id is stable across logins).
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GithubUserID,
		arg.Login,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.Login,
		&i.Email,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
